markw: camera: Add missing comma
* Missed in LA.UM.5.3-10610-89xx.0 somehow

device/xiaomi/markw/camera/QCamera2/util/QCameraDisplay.cpp:144:48: error: missing ',' between base or member initializers
  144 |       mVfe_and_mdp_freq_wiggle_filter_min_ns(0)
      |                                                ^
      |                                                ,

Change-Id: I3e24ee4dca1db632e8878802cedf2e390eb657c9